// Generated by Expo — provides type for process.env.EXPO_PUBLIC_* variables
declare namespace NodeJS {
  interface ProcessEnv {
    readonly EXPO_PUBLIC_API_URL?: string;
  }
}

declare var process: { env: NodeJS.ProcessEnv };
